Don't require .heroku-private-buildpacks to start the app

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -6,19 +6,23 @@ BUILD_DIR=${1:-}
 CACHE_DIR=${2:-}
 ENV_DIR=${3:-}
 
-for repo_url in $(cat "${BUILD_DIR}/.heroku-private-buildpacks") ; do
-    tmpdir=$(mktemp --directory private-buildpack-XXXXXXXX)
-    echo "Repo: ${repo_url}"
-    git clone "${repo_url}" "${tmpdir}"
-    cd "${tmpdir}"
-    echo "Last repo commit: $(git rev-parse HEAD)"
-    if [ -f ./bin/compile ] ; then
-        echo "Calling compile script for ${repo_url}..."
-        bash ./bin/compile "${BUILD_DIR}" "${CACHE_DIR}" "${ENV_DIR}"
-        rm -rf "${tmpdir}"
-    else
-        echo "No compile script in ${repo_url} buildpack. Aborting..."
-        rm -rf "${tmpdir}"
-        exit 1
-    fi
-done
+if [ -f "${1}/.heroku-private-buildpacks" ]; then
+  for repo_url in $(cat "${BUILD_DIR}/.heroku-private-buildpacks") ; do
+      tmpdir=$(mktemp --directory private-buildpack-XXXXXXXX)
+      echo "Repo: ${repo_url}"
+      git clone "${repo_url}" "${tmpdir}"
+      cd "${tmpdir}"
+      echo "Last repo commit: $(git rev-parse HEAD)"
+      if [ -f ./bin/compile ] ; then
+          echo "Calling compile script for ${repo_url}..."
+          bash ./bin/compile "${BUILD_DIR}" "${CACHE_DIR}" "${ENV_DIR}"
+          rm -rf "${tmpdir}"
+      else
+          echo "No compile script in ${repo_url} buildpack. Aborting..."
+          rm -rf "${tmpdir}"
+          exit 1
+      fi
+  done
+else
+  echo ".heroku-private-buildpacks file not found, skipping"
+fi
